### ISSUE TITLE
[Bug] icons father-build error

### ISSUE THREAD

**Issue by xiaohuoni** [alitajs/wufeng#12]
![image](https://user-images.githubusercontent.com/11746742/131314841-5a4de6a2-48aa-41b4-b62f-b55ce229c7c2.png)

分支: https://github.com/alitajs/wufeng/tree/feat-generate-icons
```
cd packages/icons && father-build
```

**Comment by wangxingkang** [comment]
已解决，需要配置 external 或者 使用 auto external
